/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreRaceRouteImport } from './routes/pre-race'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SplitRouteImport } from './routes/split'
import { Route as StrategyRouteImport } from './routes/strategy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreRaceRoute = PreRaceRouteImport.update({
  id: '/pre-race',
  path: '/pre-race',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitRoute = SplitRouteImport.update({
  id: '/split',
  path: '/split',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pre-race': typeof PreRaceRoute
  '/sessions': typeof SessionsRoute
  '/split': typeof SplitRoute
  '/strategy': typeof StrategyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pre-race': typeof PreRaceRoute
  '/sessions': typeof SessionsRoute
  '/split': typeof SplitRoute
  '/strategy': typeof StrategyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pre-race': typeof PreRaceRoute
  '/sessions': typeof SessionsRoute
  '/split': typeof SplitRoute
  '/strategy': typeof StrategyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pre-race' | '/sessions' | '/split' | '/strategy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pre-race' | '/sessions' | '/split' | '/strategy'
  id: '__root__' | '/' | '/pre-race' | '/sessions' | '/split' | '/strategy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreRaceRoute: typeof PreRaceRoute
  SessionsRoute: typeof SessionsRoute
  SplitRoute: typeof SplitRoute
  StrategyRoute: typeof StrategyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-race': {
      id: '/pre-race'
      path: '/pre-race'
      fullPath: '/pre-race'
      preLoaderRoute: typeof PreRaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/split': {
      id: '/split'
      path: '/split'
      fullPath: '/split'
      preLoaderRoute: typeof SplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreRaceRoute: PreRaceRoute,
  SessionsRoute: SessionsRoute,
  SplitRoute: SplitRoute,
  StrategyRoute: StrategyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
